### ISSUE TITLE
Missing channels in Guide

### ISSUE THREAD

**Issue by jcastilloalonso** [fHDHR/fHDHR_Locast#124] opened 2020-12-09 20:41 UTC
Hi,

I noticed that the amount of channels that are shown in Guide is not complete. Guide has 36 channels while Locast shows 44 available channels. Not sure what I can provide you to identify why some are missing.

Thanks!

**Comment by tharris9d** [comment] 2020-12-09 21:58
I updated to the latest version and I am also missing channels on the Locast Plex side that don't match up with fHDHR? So weird. I ran Locast2Plex to see if Plex had issues but Locast2Plex shows the proper Los Angeles Locast channels. I will upload a screenshot soon.

**Comment by deathbybandaid** [comment] 2020-12-09 22:07
Try deleting your database, starting, and verify there are no duplicate channel numbers on the channel page.

**Comment by deathbybandaid** [comment] 2020-12-09 22:09
I have some more reworking of the channels system in progress that will help with duplicate number issues

**Comment by deathbybandaid** [comment] 2020-12-09 22:15
Also to clarify, is this latest release, or main branch?

**Comment by deathbybandaid** [comment] 2020-12-09 22:18
The only recent changes that are channels/epg related are to make changes made via channel editting apply immediately

**Comment by jcastilloalonso** [comment] 2020-12-09 22:18
Using main branch. Channel order is also not correct in guide (if it helps or it's supposed to be organized)

**Comment by jcastilloalonso** [comment] 2020-12-09 22:23
Deleted data/cache/fhdhr.db and same result. I do notice they are sorted but by first letter and not numeric (like 11.2,11.3,2.1 etc.)

I notice that the main channels are missing (4.1, 5.1, 8.1, 11.1, etc.)

**Comment by deathbybandaid** [comment] 2020-12-09 22:23
Channel order isn't important

**Comment by deathbybandaid** [comment] 2020-12-09 22:24
What DMA number?

**Comment by jcastilloalonso** [comment] 2020-12-09 22:26
DMA 623

**Comment by jcastilloalonso** [comment] 2020-12-09 22:32
Sidenote, fHDHR web interface doesn't show DMA anymore, I just know it from heart :)

**Comment by deathbybandaid** [comment] 2020-12-09 22:40
Odd, I'll have to fix the 'origin' page too

**Comment by deathbybandaid** [comment] 2020-12-09 22:42
I checked the epg from locast, and those channels are still there, I will look first thing

**Comment by deathbybandaid** [comment] 2020-12-09 23:03
Are channels missing on channels page, or just the guide/xmltv

**Comment by tharris9d** [comment] 2020-12-09 23:31
Here is a screen shot of some weird behavior from the latest Main release. It is pulling phoenix stations. The highlighted stations should all be KTLA 5.1, 5.2, 5.3 from Los Angeles. It only happened on the new main release.
![image](https://user-images.githubusercontent.com/217445/101701337-91df3680-3a33-11eb-8327-4260474994d0.png)

**Comment by jcastilloalonso** [comment] 2020-12-09 23:35
> Are channels missing on channels page, or just the guide/xmltv

Just guide.

**Comment by deathbybandaid** [comment] 2020-12-10 00:00
This is why I started making releases, bugs like this get caught by the loyalists?

**Comment by deathbybandaid** [comment] 2020-12-10 03:07
Also, based on some newer threads for l2p, I think Locast may be mucking up their API

**Comment by jcastilloalonso** [comment] 2020-12-10 04:33
> This is why I started making releases, bugs like this get caught by the loyalists?

That's the idea right? a public way of doing QC.

Let me know if you want me to try older releases to see if it happens with older releases.

**Comment by deathbybandaid** [comment] 2020-12-10 06:08
I couldn't sleep, so I started fixing the 'origin' tab (Locast).

I figured out how to do a flask template outside of my main templates directory, and a tomorrow release will bring back the contents of that page.

Since the 'origin' web page will no longer be part of the core codebase, it will be easier to write custom stuff per varient of fHDHR.

Also Also, I am adding an `/api/origin` endpoint, which each varient could potentially have some extra custom tools. For Locast, it might be useful to use this new API to show DMA information for other zones in tabbed "pretty" JSON format

**Comment by deathbybandaid** [comment] 2020-12-10 06:09
I also have some plans to restructure the Guide page to merge with the xmltv page, and possibly provide additional endpoints for alternative EPG methods (such as the tvtv method added earlier today)

**Comment by deathbybandaid** [comment] 2020-12-10 06:19
I also just want to note that when coding, to sort numerically, doesn't always work cleanly, you'll often see 11 before 2 because that's how things work.

**Comment by deathbybandaid** [comment] 2020-12-10 15:37
I may have had a mental lapse, I had forgotten to push some code from my dev branch to here

https://github.com/fHDHR/fHDHR_Locast/pull/125

This include multiple adjustments to EPG/XMLTV, the addition of a new EPG method for tvtv.us, and the new 'origin' page

I've also added a couple API tools.

`/api/origin/tools?method=channels&dma=623`

````
[
    {
        "id": 231,
        "dma": 623,
        "stationId": "20371",
        "name": "KDTNDT",
        "callSign": "2.1 DYSTR",
        "logoUrl": "https://static.locastnet.org/logo/623/1606463266046_DYSTR.png",
        "active": true,
        "listings": [],
        "sequence": 10,
        "logo226Url": "https://static.locastnet.org/roku/Dallas/KDTN.png",
        "tivoId": 69024934
    },
    {
        "id": 232,
        "dma": 623,
        "stationId": "19616",
        "name": "KDFWDT",
        "callSign": "4.1 FOX",
        "logoUrl": "https://static.locastnet.org/logo/Dallas/KDFW.png",
        "active": true,
        "listings": [],
        "sequence": 20,
        "logo226Url": "https://static.locastnet.org/roku/Dallas/KDFW.png",
        "tivoId": 69022690
    },
    {
        "id": 1577971909791,
        "dma": 623,
        "stationId": "49091",
        "name": "KDFWDT2",
        "callSign": "4.2 DECADES",
        "logoUrl": "https://static.locastnet.org/logo/Dallas/DECADES.png",
        "active": true,
        "listings": [],
        "sequence": 30,
        "logo226Url": "https://fans.tmsimg.com/assets/s91415_h3_aa.png",
        "tivoId": 69031731
    },
...
]
````

`/api/origin/tools?method=zipcode&zipcode=10007`

````
{
    "DMA": "501",
    "name": "New York",
    "small_url": "https://static.locastnet.org/cities/new-york.jpg",
    "large_url": "https://static.locastnet.org/cities/background/new-york.jpg",
    "active": true,
    "announcements": [],
    "latitude": 40.71385,
    "longitude": -74.00775
}
````

Hopefully one of you has some free time to test this sooner than later

**Comment by jcastilloalonso** [comment] 2020-12-10 15:51
And they are showing up now. As always thanks a lot for your time and effort on this project. It really helps a lot! I'm ok with closing, but leaving it open for tharris9d to confirm on his side.

**Comment by tharris9d** [comment] 2020-12-10 16:52
@deathbybandaid I will be testing this morning and reply back here when done.

**Comment by tharris9d** [comment] 2020-12-10 18:50
I did a fresh install of the latest main code. If I use **zip code** in the Plex UI instead of xmltv path http://127.0.0.1:5005/api/xmltv?method=get&source=origin it works perfectly. If I use the xmltv url I get all the guide info but it's 4 hours off. All the channels are working and line up now either way. Any idea on why the guide info is off again on the xmltv.xml info?

**Comment by jcastilloalonso** [comment] 2020-12-10 19:07
> . If I use the xmltv url I get all the guide info but it's 4 hours off.

Nice catch, I also see the same here. Right now 1:00pm shows 7:00pm shows in guide. So a 6hrs difference for central time

**Comment by tharris9d** [comment] 2020-12-10 19:38
Tested #126. The advanced button is nice. I am exactly 8 hours off in the guide. It's showing the Rams vs Patriots playing now. LOL

**Comment by deathbybandaid** [comment] 2020-12-10 19:39
that's odddddd,,, as all the timestamps involved are UTC

**Comment by deathbybandaid** [comment] 2020-12-10 19:41
if you go to the xmltv page, and click the epg link, you can see the timestamps that were pulled from Locasts API

**Comment by deathbybandaid** [comment] 2020-12-10 19:44
so for me, in Eastern Time, everything seems to be correct, I can toggle between zap2it and origin, and see the same shows on for right now

**Comment by tharris9d** [comment] 2020-12-10 19:47
The xmltv looks correct too. The guide ui and Plex is pulling it incorrectly here on the west coast. Maybe a setting I missed?

<programme start="**20201210170000** +0000" stop="20201210203000 +0000" channel="11.1">
<title lang="en">NFL Football</title>
<desc lang="en">The Rams (8-4) host the Patriots (6-6) in a Super Bowl 53 rematch. New England won its sixth championship, 13-3 over Los Angeles on Feb. 3, 2019. The Patriots play consecutive games at SoFi Stadium after routing the Chargers 45-0 last week.</desc>
<sub-title lang="en">Movie: Unavailable</sub-title>
<length units="minutes">12600000</length>
<category lang="en">Football</category>
<genre lang="en">Football</genre>
<category lang="en">Sports event</category>
<genre lang="en">Sports event</genre>
<category lang="en">Sports</category>
<genre lang="en">Sports</genre>
<icon src="https://fans.tmsimg.com/assets/p18299692_tb2_v5_ab.jpg"/>
<rating system="MPAA">
<value>N/A</value>
</rating>
<new/>
</programme>

**Comment by deathbybandaid** [comment] 2020-12-10 19:49
I haven't changed anything that would have an effect on time

However, you may need to remove it from plex, restart plex, and readd.

**Comment by tharris9d** [comment] 2020-12-10 19:51
> I haven't changed anything that would have an effect on time
> 
> However, you may need to remove it from plex, restart plex, and readd.

I started with a fresh install again, added the app with xmltv url and got the same 8 hours off guide issue. If I use the zip code through plex it pulls the proper guide info. So weird.

**Comment by deathbybandaid** [comment] 2020-12-10 19:52
you can also try the zap2it and tvtv options for xmltv and see if you get the same offset

**Comment by jcastilloalonso** [comment] 2020-12-10 19:53
Here are screenshots on how it looks for me https://imgur.com/a/MknYeZA

**Comment by deathbybandaid** [comment] 2020-12-10 19:55
WAIT,, let me push something

**Comment by deathbybandaid** [comment] 2020-12-10 19:57
try now with 

https://github.com/fHDHR/fHDHR_Locast/pull/127

**Comment by deathbybandaid** [comment] 2020-12-10 20:00
#127 actually breaks something else I was working on, with some missing guide information

**Comment by jcastilloalonso** [comment] 2020-12-10 20:03
cleared cache and still shows the wrong time.

server date is CST if it makes any difference:
$ date
Thu Dec 10 14:03:09 CST 2020

**Comment by deathbybandaid** [comment] 2020-12-10 20:04
you installed #127?

**Comment by jcastilloalonso** [comment] 2020-12-10 20:09
yes sir, just did a git pull as I saw you merged it

**Comment by tharris9d** [comment] 2020-12-10 20:11
I did another fresh install for #127. I am still showing the wrong time in the guide in the web ui and in Plex. Also tvtv is giving me an internal server error. Zap2it is only giving me 3 channels.

**Comment by deathbybandaid** [comment] 2020-12-10 20:13
@tharris9d in your config set 

````
[tvtv]
postalcode = 
lineuptype = ota
````

**Comment by deathbybandaid** [comment] 2020-12-10 20:13
Are either of you using a VPS or anything like that?

**Comment by deathbybandaid** [comment] 2020-12-10 20:15
well, I just doublechecked the Locast EPG, and I'm reverting #127 as that has no effect here

**Comment by jcastilloalonso** [comment] 2020-12-10 20:18
Using CentOS 7 with Python 3.7 manually compiled, home server no VPS or anything.

**Comment by deathbybandaid** [comment] 2020-12-10 20:23
This is confusing, I can't think of anything that would offset your guide data, and mine works perfectly

**Comment by jcastilloalonso** [comment] 2020-12-10 20:26
me neither, 8 hrs is more than difference with UTC

**Comment by tharris9d** [comment] 2020-12-10 20:28
I just tested zap2it and I'm getting tomorrow in the xmltv date. http://127.0.0.1:5006/api/xmltv?method=get&source=zap2it
`<programme start="2020**1211**010000 +0000" stop="20201211043000 +0000" channel="11.1">
<title lang="en">NFL Football</title>
<desc lang="en">The Rams (8-4) host `

**Comment by deathbybandaid** [comment] 2020-12-10 20:29
Just going to talk my way through this:

1) we pull data from https://api.locastnet.org/api/watch/epg/DMA_NUMBER_HERE

2) This is a list of dictionaries, the dictionaries contain channel information (same place we get channel info to begin with)

3) each channel dictionary then has a list of event/program dictionaries `listings`.

4) each listing has an epoch timestamp `startTime`  and a `duration` in seconds (endtime is calculated from this info as well)

5) epoch timestamps should be UTC, and are then converted to xmltv format. "%Y%m%d%H%M%S +0000"

**Comment by tharris9d** [comment] 2020-12-10 20:31
I got tvtv working but the most of the content thumbnails are not coming through in the webui.

**Comment by deathbybandaid** [comment] 2020-12-10 20:32
yeah, tvtv still needs some work

**Comment by jcastilloalonso** [comment] 2020-12-10 20:33
Sorry don't know python so can't help much, thinking on logic wise, there might be a mistake in the calculation from UTC that does not occur in your timezone. Is there any dump I can provide you to analyze?

**Comment by deathbybandaid** [comment] 2020-12-10 20:33
not really,,, there shouldn't be any time conversion whatsoever

**Comment by jcastilloalonso** [comment] 2020-12-10 20:34
If epoch timestamps are UTC, how do we know what time to show as current?

**Comment by deathbybandaid** [comment] 2020-12-10 20:34
https://www.unixtimestamp.com/index.php

**Comment by deathbybandaid** [comment] 2020-12-10 20:35
if you copy a start time from Locast API into there, you'll get the UTC time output

**Comment by jcastilloalonso** [comment] 2020-12-10 20:35
right, then why does it show the future shows as present?  I'll try to dig into this this evening.

**Comment by deathbybandaid** [comment] 2020-12-10 20:36
Plex/Emby should be the only thing doing any time conversion

**Comment by jcastilloalonso** [comment] 2020-12-10 20:36
How about the web guide in fHDHR?

**Comment by deathbybandaid** [comment] 2020-12-10 20:37
do either of you use another fHDHR varient? can you see if those schedules look fine?

**Comment by deathbybandaid** [comment] 2020-12-10 20:38
web guide simply gets uses `utcnow()` to find what's currently on, intentionally not listing a local time

**Comment by deathbybandaid** [comment] 2020-12-10 20:39
it loops through the listings per channel and finds the first entry that meets the criteria `if start_time <= nowtime <= end_time:`

**Comment by deathbybandaid** [comment] 2020-12-10 21:10
I'm also finding that Locast misses a few channels in their EPG, so I'm coding in some Blocks scheduling to fill it in

**Comment by deathbybandaid** [comment] 2020-12-10 21:29
Looks like Locast has channels with EPG data, but not for every hour?

**Comment by tharris9d** [comment] 2020-12-10 22:21
http://127.0.0.1:5006/guide?source=tvtv
Missing some thumbnails but the Content Title and Description are accurate. 
http://127.0.0.1:5006/guide?source=origin
Origin is still 8 hours off.

**Comment by deathbybandaid** [comment] 2020-12-10 22:29
The hard thing to diagnose is that I changed nothing about how the timestamps work since a prior build.

If you install the last release, does it work?

**Comment by tharris9d** [comment] 2020-12-10 22:50
I updated fHDHR_PlutoTV to the latest Main version and the web ui guide is correct. I compared with the PlutoTV Roku app.

**Comment by deathbybandaid** [comment] 2020-12-11 15:18
Okay guys, here's some interesting development,,, I'm coding in the ability to detect missing timeslots, and generate Program information for those times. I also coded in some stuff to create block scheduling for missing channels.

here's where it gets interesting. I added some debug print lines for my testing, and here's what happens with my Locast New York DMA 501, 49 channels:

![image](https://user-images.githubusercontent.com/18010545/101920717-21065e80-3b9a-11eb-992c-754c6ac93577.png)

**Comment by deathbybandaid** [comment] 2020-12-11 15:25
I think I'm going to change some EPG handling stuff, and store epoch style timestamps instead of datetime style timestamps, and do the conversion to xmltv format just for the xmltv generation

**Comment by jcastilloalonso** [comment] 2020-12-11 16:10
> http://127.0.0.1:5006/guide?source=tvtv
> Missing some thumbnails but the Content Title and Description are accurate.
> http://127.0.0.1:5006/guide?source=origin
> Origin is still 8 hours off.

I actually get an 500 internal Server Error using tvtv. zap2it only shows 6 channels.



> Okay guys, here's some interesting development,,, I'm coding in the ability to detect missing timeslots, and generate Program information for those times. I also coded in some stuff to create block scheduling for missing channels.
> 
> here's where it gets interesting. I added some debug print lines for my testing, and here's what happens with my Locast New York DMA 501, 49 channels:
> 

That looks weird... I like your idea of moving the conversion over to xmltv generation. Hope it helps

**Comment by deathbybandaid** [comment] 2020-12-11 16:27
if that fixes it, I may try to find something to try to override system time with UTC

**Comment by jcastilloalonso** [comment] 2020-12-11 18:32
> I actually get an 500 internal Server Error using tvtv. zap2it only shows 6 channels.

Here's the exception I got when trying tvtv:

fHDHR - ERROR - Exception on /guide [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/fHDHR_Locast/fHDHR_web/pages/guide_html.py", line 15, in __call__
    return self.get(*args)
  File "/opt/fHDHR_Locast/fHDHR_web/pages/guide_html.py", line 28, in get
    for channel in self.fhdhr.device.epg.whats_on_allchans(source):
  File "/opt/fHDHR_Locast/fHDHR/device/epg/__init__.py", line 88, in whats_on_allchans
    epgdict = self.get_epg(method)
  File "/opt/fHDHR_Locast/fHDHR/device/epg/__init__.py", line 117, in get_epg
    self.update(method)
  File "/opt/fHDHR_Locast/fHDHR/device/epg/__init__.py", line 177, in update
    programguide = self.epg_handling[method].update_epg()
  File "/opt/fHDHR_Locast/alternative_epg/tvtv/__init__.py", line 52, in update_epg
    cached_items = self.get_cached(dates_to_pull)
  File "/opt/fHDHR_Locast/alternative_epg/tvtv/__init__.py", line 112, in get_cached
    self.get_cached_item(str(datesdict["start"]), url)
  File "/opt/fHDHR_Locast/alternative_epg/tvtv/__init__.py", line 128, in get_cached_item
    result = resp.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jcastilloalonso** [comment] 2020-12-11 18:36
> if that fixes it, I may try to find something to try to override system time with UTC

Switching to UTC fixed origin for me. tvtv still sending the same Internal Error 500

# timedatectl
      Local time: Fri 2020-12-11 12:33:23 CST
  Universal time: Fri 2020-12-11 18:33:23 UTC
        RTC time: Fri 2020-12-11 18:33:23
       Time zone: America/Chicago (CST, -0600)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: no
 Last DST change: DST ended at
                  Sun 2020-11-01 01:59:59 CDT
                  Sun 2020-11-01 01:00:00 CST
 Next DST change: DST begins (the clock jumps one hour forward) at
                  Sun 2021-03-14 01:59:59 CST
                  Sun 2021-03-14 03:00:00 CDT
# timedatectl set-timezone UTC
# timedatectl
      Local time: Fri 2020-12-11 18:34:02 UTC
  Universal time: Fri 2020-12-11 18:34:02 UTC
        RTC time: Fri 2020-12-11 18:34:02
       Time zone: UTC (UTC, +0000)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: n/a

**Comment by deathbybandaid** [comment] 2020-12-11 18:38
> @tharris9d in your config set
> 
> ```
> [tvtv]
> postalcode = 
> lineuptype = ota
> ```

@jcastilloalonso

**Comment by jcastilloalonso** [comment] 2020-12-11 18:40
Changing timezone requires fHDHR to be restarted for guide to be fixed. Otherwise, it stays broken even if I purge cache.

**Comment by jcastilloalonso** [comment] 2020-12-11 18:42
> > @tharris9d in your config set
> > ```
> > [tvtv]
> > postalcode = 
> > lineuptype = ota
> > ```
> 
> @jcastilloalonso

Fixed tvtv, derp on my end... tvtv shows correct show in both timezones.

**Comment by deathbybandaid** [comment] 2020-12-11 18:47
it's on my list to figure out hos to manage the threads from the webUI, so that you can completely manage from the webUI, which is one of the key factors in reaching version 1.0

**Comment by deathbybandaid** [comment] 2020-12-11 21:09
Guys I'm about to drop a major overhaul of the EPG system, and it may fix all the issue, or at least some of them

**Comment by deathbybandaid** [comment] 2020-12-11 21:17
pushed some sweet sweet code

**Comment by deathbybandaid** [comment] 2020-12-11 21:19
turns out some of my code to dedupe entries was potentially part of the problem, and I've implemented something to counter that

**Comment by deathbybandaid** [comment] 2020-12-11 21:23
If the most recent push doesn't fix your issues with offset, I'll look into a way for the script environment to lock to UTC

**Comment by jcastilloalonso** [comment] 2020-12-11 21:24
Nice work! Just pulled and restarted and it's day and night, channel order fixed, correct time regardless of timezone (tried both) for origin, yet zap2it and tvtv sending 500 Internal Error.
 http://plexserver:5009/guide?source=zap2it:

fHDHR - ERROR - Exception on /guide [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/fHDHR_Locast/fHDHR_web/pages/guide_html.py", line 15, in __call__
    return self.get(*args)
  File "/opt/fHDHR_Locast/fHDHR_web/pages/guide_html.py", line 47, in get
    whatson = self.fhdhr.device.epg.whats_on_allchans(source)
  File "/opt/fHDHR_Locast/fHDHR/device/epg/__init__.py", line 99, in whats_on_allchans
    whatson = self.whats_on_now(channel_number, method)
  File "/opt/fHDHR_Locast/fHDHR/device/epg/__init__.py", line 70, in whats_on_now
    if listing["time_start"] <= nowtime <= listing["time_end"]:
TypeError: '<=' not supported between instances of 'str' and 'float'

http://plexserver:5009/guide?source=tvtv :
fHDHR - ERROR - Exception on /guide [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/fHDHR_Locast/fHDHR_web/pages/guide_html.py", line 15, in __call__
    return self.get(*args)
  File "/opt/fHDHR_Locast/fHDHR_web/pages/guide_html.py", line 47, in get
    whatson = self.fhdhr.device.epg.whats_on_allchans(source)
  File "/opt/fHDHR_Locast/fHDHR/device/epg/__init__.py", line 99, in whats_on_allchans
    whatson = self.whats_on_now(channel_number, method)
  File "/opt/fHDHR_Locast/fHDHR/device/epg/__init__.py", line 70, in whats_on_now
    if listing["time_start"] <= nowtime <= listing["time_end"]:
TypeError: '<=' not supported between instances of 'str' and 'float'

**Comment by deathbybandaid** [comment] 2020-12-11 21:28
push the update button for those on the xmltv page

**Comment by jcastilloalonso** [comment] 2020-12-11 21:30
> push the update button for those on the xmltv page

And that fixed it, didn't think of the cache after a rebuild haha

**Comment by deathbybandaid** [comment] 2020-12-11 21:46
Zap and origin are good though?

**Comment by jcastilloalonso** [comment] 2020-12-11 21:51
> Zap and origin are good though?

Origin good, Zap and tvtv also wrong with America/Chicago timezone, UTC timezone fixes it.

**Comment by tharris9d** [comment] 2020-12-11 22:15
Origin is all correct now in the latest main version web ui. Zap2it and TVTV are missing thumbs titles and descriptions. Time zone is now correct. Thanks! I will test in Plex now too.

**Comment by tharris9d** [comment] 2020-12-11 22:28
Using Plex the channels all load using http://127.0.0.1:5005/api/xmltv?method=get&source=origin as my xmltv link. However the guide doesn't load in Plex. 0 information. I tried restarting the Plex Server, clearing cache, updating, rebooting.

**Comment by deathbybandaid** [comment] 2020-12-12 09:45
Try deleting the dvr in plex, restart plex, refresh browser, and readd

**Comment by deathbybandaid** [comment] 2020-12-14 18:44
anybody want to test #132 with a fresh db?

**Comment by jcastilloalonso** [comment] 2020-12-14 22:34
> anybody want to test #132 with a fresh db?

Origin still working correctly except the Content Remaining Time still showing pretty much a yr.
tvtv still showing 8hrs ago content
zap2it not pulling anything from guide, just channels. I have the following in my config.ini for it:

[zap2it]
postalcode = 750xx (do have full zip code just took off the last 2 for privacy, but can provide if needed)

**Comment by tharris9d** [comment] 2020-12-14 22:49
Tested new code. Origin pulls channels into plex but nothing shows on Plex Guide. Everything shows fine in the fHDHR_locast web-ui. @jcastilloalonso are all the origin channels with content showing up in your plex guide? Using the http://127.0.0.1:port/api/xmltv?method=get&source=origin link?

**Comment by jcastilloalonso** [comment] 2020-12-15 06:39
> @jcastilloalonso are all the origin channels with content showing up in your plex guide? Using the http://127.0.0.1:port/api/xmltv?method=get&source=origin link?

Yeah it seems to  be working over here

**Comment by tharris9d** [comment] 2020-12-15 18:18
I have tried everything but the channels with airing data will not load into Plex using the latest version. It starts with 0% then just finishes without loading data. When you hit view guide nothing is there. I tried downloading the xml file and loading it directly with the exact same results. 
I then tried an older release 4.5 and it works fine except for the 8 hour time difference.
I zipped up both xml files to see if something is different. Please take a look. 
FYI: Everything works fine in the Web UI.
[locast_xmltv.zip](https://github.com/fHDHR/fHDHR_Locast/files/5697715/locast_xmltv.zip)

**Comment by deathbybandaid** [comment] 2020-12-15 21:51
@tharris9d I really don't know what to do to fix it for you. Try ALL of the below steps, IN ORDER, and report back

1) Delete DVR in plex
2) stop your plex service

3) stop fHDHR_Locast
4) Delete database file

5) start fHDHR_Locast
6) start plex service

7) add the dvr to plex

**Comment by deathbybandaid** [comment] 2020-12-15 21:52
It's confirmed working properly for myself and @jcastilloalonso

**Comment by deathbybandaid** [comment] 2020-12-15 21:53
quick edit on the above steps

**Comment by deathbybandaid** [comment] 2020-12-18 01:13
@tharris9d please try as of #138

**Comment by tharris9d** [comment] 2020-12-18 01:30
Will test it now..

**Comment by tharris9d** [comment] 2020-12-18 01:39
Woo hoo....The guide loaded. Unfortunately 9pm is showing the 5am news on CBS. The guide times are off again. So close.. I added to restarted plex after deleting db and updating data and restarting the app. The whole enchilada.

**Comment by deathbybandaid** [comment] 2020-12-18 01:42
Idk what your setup is, but everything is utc

**Comment by deathbybandaid** [comment] 2020-12-18 02:43
I think in the morning, I'll add a config option for xmltv offset

**Comment by deathbybandaid** [comment] 2020-12-18 14:00
@tharris9d please give #139 a try.

in your config, you can do `[epg]xmltv_offset=` to set the offset that displays in the xmltv file.

The default is "+0000", but should work with +/-HHMM

Additionally, if it's only one xmltv/epg source that you are having the offset issue with, you can do `[locast]xmltv_offset` or `[zap2it]xmltv_offset` or `[tvtv]xmltv_offset`

**Comment by tharris9d** [comment] 2020-12-18 16:39
I set the offset for locast. The xmltv isn't loading the guide info again. All the channels load fine but when it initializes the guide it hits 0% and ends. No guide show.

**Comment by deathbybandaid** [comment] 2020-12-18 17:33
What did you set the offset to

**Comment by tharris9d** [comment] 2020-12-18 18:06
@deathbybandaid I figured it out. I didn't put the +- signs. After some experimenting I have it working with locast -0800 for Los Angeles
Thanks for this new option! I think we can close this ticket now and move on to the next....
Congrats!

**Comment by tharris9d** [comment] 2020-12-18 18:13
Will you be adding the offset into the webui settings?

**Comment by deathbybandaid** [comment] 2020-12-18 18:16
not until you've tested it for a subversion or two

**Comment by tharris9d** [comment] 2020-12-18 18:29
Makes sense...I will test again in xteve and see if it fixes the xteve issues.

**Comment by jcastilloalonso** [comment] 2020-12-18 19:32
I'm having problem with tvrv and offset. Don't see any changes. My config.ini looks like this:

[tvtv]
postalcode = 750xx
lineuptype = ota
xmltv_offset = -0600

Regardless of the offset number (tried -0800 and +0600) the guide remains the same.

**Comment by deathbybandaid** [comment] 2020-12-18 21:51
The guide page is just using the timestamps which are utc, compared to utcnow.

The xmltv will display the offset

**Comment by deathbybandaid** [comment] 2020-12-19 13:59
This issue thread is out of hand. I'm closing it. You guys need to be better about seperate threads for issues.

**Closed by deathbybandaid** 2020-12-19 13:59 UTC
